// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/apple-touch-icon.png"
    | "/favicon-96x96.png"
    | "/favicon.svg"
    | "/manifest.json"
    | "/newtab.html"
    | "/web-app-manifest-192x192.png"
    | "/web-app-manifest-512x512.png"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
